version: "3.9"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "manager_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  webapp:
    restart: always
    build:
      context: ./webapp
    ports:
      - "8000:8000"
    command: [ "python3", "./src/manage.py", "runserver", "0.0.0.0:8000" ]

  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: ./webapp
    command: ['celery', '--workdir=./src', '-A', 'config', 'worker']

  celery-beats:
    restart: always
    build:
      context: ./webapp
    command: ['celery', '--workdir=./src', '-A', 'config', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']
